name: matrix-file-upload
description: Send a file with subject to a matrix channel
author: daedric (ricardo.dra.vieira@gmail.com)
inputs:
  server:
    description: "Matrix server hostname"
    default: "matrix.org"
    required: false
  room_id:
    description: "Matrix room ID, specified in channels advanced settings"
    default: ""
    required: true
  access_token:
    description: "Access token required to send to matrix server"
    default: ""
    required: true
  message:
    description: "Message to send in markdown or html format"
    default: ""
    required: true
  subject:
    description: "Subject of message in plaintext format"
    default: ""
    required: false
runs:
  using: docker
  image: 'Dockerfile'
branding:
  icon: 'message-square'
  color: 'gray-dark'
